CXX ?= g++

DEBUG ?= 1
ifeq ($(DEBUG), 1)
    CXXFLAGS += -g
else
    CXXFLAGS += -O2

endif

server: main.cpp  ./timer/lst_timer.cpp ./http/http_conn.cpp ./log/log.cpp ./logic/logic.cpp ./logic/user.cpp ./logic/login.cpp ./logic/menus.cpp ./logic/rights.cpp ./logic/roles.cpp ./CGImysql/sql_connection_pool.cpp  webserver.cpp config.cpp
	$(CXX) -o server  $^ $(CXXFLAGS) -lpthread -lmysqlclient -ljsoncpp -lcrypto

clean:
	rm  -r server
